// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRKeQCKorBlf-Cj9i8FSm4I_FjcQws90',
    appId: '1:24024320121:web:ff76ad4e31c09be4192ca8',
    messagingSenderId: '24024320121',
    projectId: 'zalo-chat-28514',
    authDomain: 'zalo-chat-28514.firebaseapp.com',
    databaseURL: 'https://zalo-chat-28514-default-rtdb.firebaseio.com',
    storageBucket: 'zalo-chat-28514.appspot.com',
    measurementId: 'G-8PQ4JE5EG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfrx7rkWi2LyzUE-ynlUTzk6tPfmID74Q',
    appId: '1:24024320121:android:b5ea353e76e6680b192ca8',
    messagingSenderId: '24024320121',
    projectId: 'zalo-chat-28514',
    databaseURL: 'https://zalo-chat-28514-default-rtdb.firebaseio.com',
    storageBucket: 'zalo-chat-28514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCV47J1AdFrSJ1GXuB2XUAL0_sKp_mzKw',
    appId: '1:24024320121:ios:c86f863e19cbc0bf192ca8',
    messagingSenderId: '24024320121',
    projectId: 'zalo-chat-28514',
    databaseURL: 'https://zalo-chat-28514-default-rtdb.firebaseio.com',
    storageBucket: 'zalo-chat-28514.appspot.com',
    iosBundleId: 'com.example.zalochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCV47J1AdFrSJ1GXuB2XUAL0_sKp_mzKw',
    appId: '1:24024320121:ios:68797e41bf9034ab192ca8',
    messagingSenderId: '24024320121',
    projectId: 'zalo-chat-28514',
    databaseURL: 'https://zalo-chat-28514-default-rtdb.firebaseio.com',
    storageBucket: 'zalo-chat-28514.appspot.com',
    iosBundleId: 'com.example.zalochat.RunnerTests',
  );
}
